name: Generate Snake Contribution Graph

on:
  schedule:
    # Run every 6 hours (adjust if you want)
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      # Generate snake graph with custom colors & outputs
      - uses: Platane/snk@v3
        with:
          github_user_name: anishrajpandey
          outputs: |
            graphs/anish-snake.svg?color_snake=#22c55e&color_dots=#d1fae5,#86efac,#4ade80,#22c55e,#16a34a
            graphs/anish-snake-dark.svg?palette=github-dark
            graphs/anish-snake.gif?color_snake=#22c55e&color_dots=#d1fae5,#86efac,#4ade80,#22c55e,#16a34a

      # Show git status for debugging
      - run: git status

      # Commit and push changes back to the default branch
      - name: Commit and push updated snake graphs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add graphs/
          git commit -m "Update contribution snake graph [skip ci]" || echo "No changes to commit"
          git push origin HEAD:master

